"""empty message

Revision ID: 0958f770df5c
Revises: c02d3f8d2211
Create Date: 2025-11-13 15:06:50.251172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0958f770df5c'
down_revision = 'c02d3f8d2211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('suspension_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('suspension_until')
        batch_op.drop_column('banned_at')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('account_status')
        batch_op.drop_column('banned_by')
        batch_op.drop_column('suspension_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspension_reason', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('banned_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('banned_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('suspension_until', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_ibfk_1'), 'users', ['banned_by'], ['id'])

    op.drop_table('account_actions')
    # ### end Alembic commands ###
