"""empty message

Revision ID: c02d3f8d2211
Revises: 86c16f7b131f
Create Date: 2025-11-13 06:19:27.756436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c02d3f8d2211'
down_revision = '86c16f7b131f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('suspension_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('suspension_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('banned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('banned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['banned_by'], ['id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('banned_by')
        batch_op.drop_column('banned_at')
        batch_op.drop_column('suspension_until')
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('account_status')

    op.drop_table('documents')
    # ### end Alembic commands ###
